### ISSUE TITLE
Role Member menu appearing in top left corner, cannot be moved or closed.

### ISSUE THREAD

**Issue by wezu123** [rauenzi/BetterDiscordAddons#112]
I've installed this plugin yesterday, before the release of 0.1.7, and got a problem that I couldn't do anything with the menu. After today's update I can scroll the list and open user profile menu, but I can only open Role Members from server list, role mentions stopped working with this update. To close the menu I have to restart the plugin each time.

If you could add context menu for users, it would be fantastic, that's a feature that would help me a lot.

I hope you can fix it, or help me make it work, because I really love this idea and it would make managing my server a breeze. Thanks for your work!

RoleMembers v0.1.7
ZeresPluginLibrary v1.2.3

**Comment by rauenzi** [comment]
Role mentions should now work with this update, it had been confirmed not working in the previous version.

Not sure what you mean by "add context menu for users"

Please update the library and reload, it is outdated.

**Comment by wezu123** [comment]
Thanks for the tip with updating the library, it opens properly now.
What I meant with context menu is right-click that opens the long list of options, not left-click that opens just the user card.

I still can't get role mentions to work, even after updating the library. For some reason it worked for me in 0.1.6. 

Thanks for the quick response!

**Comment by rauenzi** [comment]
So you mean a submenu that has all the users in it instead of the popout with search bar?

I will look into it, but it's still working on my end

**Comment by wezu123** [comment]
Sorry for confusion, I mean this menu: https://imgur.com/a/kH07kHp
I want to kick, ban, and open DM history, but this menu won't open in Role Member like it does everywhere else.

**Comment by rauenzi** [comment]
What would role members do there?

**Comment by rauenzi** [comment]
Stale.
